### PR TITLE
update checksum

### PR DESCRIPTION
**Pull request by jamesmkrieger**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

The automatic pull request didn't have the right sha256 checksum and still installs prody 2.0.1 so this is a fix for that

### CODE REVIEW

**Comment by simonbray** [comment]
From the logs: `RuntimeError: SHA256 mismatch: '1253f21717cdca7637784080e7982c04f3a6402b6b6a2f49d56cfcaa1be7ed16' != 'ed23deb8f4a54b856829e3621b574ec38522a1f141dbb7b2ba446d1fd739fbb8'`

What's the reason to update it actually?

**Comment by jamesmkrieger** [comment]
I'm trying that now. I also thought about that. I'll let you know what happens

**Comment by jamesmkrieger** [comment]
ok, that worked:

```
## Package Plan ##

  environment location: /home/jkrieger/anaconda3/envs/conda_prody

  added / updated specs:
    - prody=2.0.2


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cryptography-36.0.0        |   py39h9ce1e76_0         1.3 MB
    prody-2.0.2                |   py39he80948d_0         8.2 MB  conda-forge
    ------------------------------------------------------------
                                           Total:         9.6 MB

The following NEW packages will be INSTALLED:

  biopython          conda-forge/linux-64::biopython-1.79-py39h3811e60_1
  brotlipy           conda-forge/linux-64::brotlipy-0.7.0-py39h3811e60_1003
  cffi               conda-forge/linux-64::cffi-1.15.0-py39h4bc2ebd_0
  charset-normalizer conda-forge/noarch::charset-normalizer-2.0.12-pyhd8ed1ab_0
  cryptography       pkgs/main/linux-64::cryptography-36.0.0-py39h9ce1e76_0
  idna               conda-forge/noarch::idna-3.3-pyhd8ed1ab_0
  prody              conda-forge/linux-64::prody-2.0.2-py39he80948d_0
  pycparser          conda-forge/noarch::pycparser-2.21-pyhd8ed1ab_0
  pyopenssl          conda-forge/noarch::pyopenssl-22.0.0-pyhd8ed1ab_0
  pysocks            conda-forge/linux-64::pysocks-1.7.1-py39hf3d152e_4
  requests           conda-forge/noarch::requests-2.27.1-pyhd8ed1ab_0
  scipy              conda-forge/linux-64::scipy-1.8.0-py39hee8e79c_1
  urllib3            conda-forge/noarch::urllib3-1.26.8-pyhd8ed1ab_1


Proceed ([y]/n)? y


Downloading and Extracting Packages
prody-2.0.2          | 8.2 MB    | ################################################################################## | 100% 
cryptography-36.0.0  | 1.3 MB    | ################################################################################## | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

```
Python 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:24:37) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.0.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import prody

In [2]: prody.__version__
Out[2]: '2.0.2'

In [3]: 

In [3]: from prody import *

In [4]: y = searchPfam("P19491", timeout=1000)
@> Retrieving Pfam search results: https://pfam.xfam.org/protein/P19491?output=xml
/home/jkrieger/anaconda3/envs/conda_prody/lib/python3.9/site-packages/urllib3/connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'pfam.xfam.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
@> Pfam search completed in 0.71s.
@> Query 'P19491' matched 3 Pfam families.
```

**Comment by jamesmkrieger** [comment]
Pull request closed

**Comment by jamesmkrieger** [comment]
Thanks very much for your patience

**Pull request closed without merging**
